name: startup_namer
description: A startup-namer app.
version: 1.0.0+1

# #docregion dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
# #enddocregion dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.4.0
  flutter_launcher_icons: "^0.7.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/gg.jpg"

flutter:
  uses-material-design: true
  assets:
    -images/gg.jpg

